services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:${PORT}"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    # Add host.docker.internal to extra_hosts to allow the container to connect to the host machine
    extra_hosts:
      - "host.docker.internal:host-gateway"
